# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarasapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscode',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.DeleteModel(
            name='SmsCode',
        ),
    ]
