# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarasapp', '0003_auto_20160217_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
