# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('injuries', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('vehicle', models.CharField(max_length=100, null=True)),
                ('lon', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
