# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='lat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='lon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
